### ISSUE TITLE
Crash when using some keyboard shortcuts

### ISSUE THREAD

**Issue by Barben360** [flozz/nautilus-terminal#28] opened 2018-12-07 13:18 UTC
When in Nautilus and pressing CTRL+H to show/hide hidden folders and nautilus-terminal is active, nautilus crashes. This does not happen with nautilus-terminal not active.

**Comment by flozz** [comment] 2018-12-10 12:10
Hello,

I am unable to reproduce your issue with the `master` branch on Ubuntu 18.10. Can you provide more information:

* Linux Distribution and version
* Nautilus version

:)

**Comment by flozz** [comment] 2018-12-10 12:30
Ok, thank you for the feedback.

It is possible that Nautilus Terminal makes Nautilus less stable as it is a hack over the Nautilus Extension API and as it touch things it should not...

Anyway, I close the issue, please re-open it if you have any information ;)

**Closed by flozz** 2018-12-10 12:30 UTC
