### ISSUE TITLE
Customizable ansi colors?

### ISSUE THREAD

**Issue by GiovanniCardamone** [flozz/nautilus-terminal#81] opened 2022-09-05 13:59 UTC
I am using dark gtk theme, and the default ansi color are not really eyes-friendly, would be nice to have configurable ansi color 

example

![Screenshot from 2022-09-05 15-57-08](https://user-images.githubusercontent.com/5117748/188466163-c8578897-8bce-485f-96a4-12073cd92bb2.png)

![Screenshot from 2022-09-05 15-58-38](https://user-images.githubusercontent.com/5117748/188466469-1edb6f34-05cb-49f8-a7ac-ded6ce2a9e0f.png)

**Comment by flozz** [comment] 2022-09-05 15:00
Hello,

Yes default VTE colors are ugly. It would be cool to add settings to customize them but I have no time / motivation to do it currently. I would accept a PR if someone is motivated enough to implement this. :)

NOTE: duplicate of #76

**Comment by Acervans** [comment] 2022-10-02 18:03
Managed to hardcode them as a temporary solution. Just replace lines 327-343 from `/usr/lib/python3.X/nautilus_terminal.py` with:
```
foreground = Gdk.RGBA(
    fg_color[0] / 255.0,
    fg_color[1] / 255.0,
    fg_color[2] / 255.0,
    1,
)
background = Gdk.RGBA(
    bg_color[0] / 255.0,
    bg_color[1] / 255.0,
    bg_color[2] / 255.0,
    1,
)

palette_color_codes = ["#171421", "#C01C28", "#26A269", "#A2734C", "#12488B", "#A347BA", "#2AA1B3", "#D0CFCC",  # Palette colors
                       "#5E5C64", "#F66151", "#33D17A", "#E9AD0C", "#2A7BDE", "#C061CB", "#33C7DE", "#FFFFFF"]  # Bright counterparts

palette_colors = []
for color_code in palette_color_codes:
    if not color_helpers.is_color(color_code):
        color_code = 'White' # Invalid colors default to white

    color = color_helpers.parse_color_string(color_code)
    color = Gdk.RGBA(
        color[0] / 255.0,
        color[1] / 255.0,
        color[2] / 255.0,
        1
    )
    palette_colors.append(color)

self._ui_terminal.set_colors(foreground, background, palette_colors)
```
And restart it with `nautilus -q`.

Here I used the default GNOME colors from my terminal profile. Of course, change the palette_color_codes with the ones you want. The palette sizes must be 0, 8, 16, 232 or 256.
Additionally, and as a personal preference I set the bold colors to bright with `self._ui_terminal.set_bold_is_bright(True)` at the end.

**Comment by flozz** [comment] 2022-10-03 13:07
The @Acervans will be released in the next Nautilus Temrinal version very soon :)

**Closed by flozz** 2022-10-03 13:07 UTC
Labels: enhancement
