### ISSUE TITLE
nautilus_terminal.crowbar not found

### ISSUE THREAD

**Issue by imkzh** [flozz/nautilus-terminal#18] opened 2018-09-17 06:27 UTC
i installed nautilus-terminal and nothing happened, and here's the console output:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar
Traceback (most recent call last):
  File "/usr/local/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar

```
but when i invoke python manually and try
```from nautilus_terminal.crowbar import Crowbar```
the module was imported without error.

**Comment by flozz** [comment] 2018-09-17 11:51
Hello,

This can be caused by different version of Python (the one used by nautilus-python is probably different than the one that was used to install nautilus-terminal).

* What is your Linux distribution?
* What is your python version (`python --version`)
* can you add this following file to `/usr/share/nautilus-python/extensions/get_version.py` and then reastart nautilus from a terminal to show the output (`nautilus -q && nautilus`):

```python
import sys
print("#################################")
print(sys.version)
print("#################################")
```

**Comment by imkzh** [comment] 2018-09-17 12:11
sorry for the inconvenience, I've resolved this problem myself, it was caused by pip.
for some reason the default pip is for python3 on my machine:
```
$ pip --version
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```
and i simply install nautilus-terminal by `pip install .`, so the package was installed to python3 and could not found by default interpreter python2.

after install pip2 and run `pip2 install .` in repository root, the embedded terminal showed up.

and here's my Linux distribution and python version:
```
$ uname -a
Linux MyUbuntu 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 2.7.12

$ python3 --version
Python 3.5.2
```

nautilus extension reported:
```
######
sys.version: 
2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
sys.executable: 
/usr/bin/python
######
```

**Comment by flozz** [comment] 2018-09-18 11:26
Ok,

I close this issue as it is resolved :)

**Closed by flozz** 2018-09-18 11:26 UTC
