### ISSUE TITLE
Navigating through directories using nautilus terminal

### ISSUE THREAD

**Issue by fernent** [flozz/nautilus-terminal#45] opened 2020-05-27 11:39 UTC
Here is my configuration :

```

       :-------------------::        ----------------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora 32 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: HP EliteBook 840 G5 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.6.14-300.fc32.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 10 mins 
,------------:MMMd--------    ---:   Packages: 5600 (rpm) 
:------------:MMMd-------    .---:   Shell: zsh 5.8 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Adwaita 
:-    ------/hMMMy------------:      Theme: Adwaita [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Adwaita [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: gnome-terminal 
:------:://:-------------::          CPU: Intel i7-8550U (8) @ 4.000GHz 
:---------------------://            GPU: Intel UHD Graphics 620 
                                     Memory: 3161MiB / 7798MiB 
```

I am using nautilus 3.36.2 and I installed Nautilus Terminal 3.
When I navigate through my directories using the nautilus GUI, the current directory of the nautilus terminal is changing.
However, if I am navigating through my directories using the nautilus terminal, the current directory of the nautilus GUI is unchanged.

Is it the normal behavior of this extension ?

**Comment by flozz** [comment] 2020-05-27 11:48
Hello,

Yes it is the normal behavior of Nautilus Terminal. Updating Nautilus while cd-ing in the terminal would be a great feature, but it is to complicated to do... See #21 for more details 😉️

**Comment by fernent** [comment] 2020-05-27 11:52
Ok I am too greedy, merci pour le boulot.

**Comment by flozz** [comment] 2020-05-27 11:53
Thank you, I close the issue as it is a duplicate of #21. :)

**Closed by flozz** 2020-05-27 11:53 UTC
