### ISSUE TITLE
Auto CD not working #2

### ISSUE THREAD

**Issue by ghost** [flozz/nautilus-terminal#17] opened 2018-09-04 23:21 UTC
Sorry icannot reopen the Issue because you closed it.

>   File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 24, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text, len(text) + 1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/crowbar.py", line 25, in _on_parent_set
    create_or_update_natilus_terminal(self)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 53, in create_or_update_natilus_terminal
    vpanel._nt_instance.change_directory(crowbar.path)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 135, in change_directory
    self._inject_command(" cd %s" % helpers.escape_path_for_shell(self._cwd))
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 175, in _inject_command
    _vte_terminal_feed_child(self._ui_terminal, "%s\n" % command)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 27, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text)
TypeError: Must be number, not str

Tested on archlinux with latest updates
`python <<< "from gi.repository import Vte; print('v%i.%i.%i' % (Vte.get_major_version(), Vte.get_minor_version(), Vte.get_micro_version()))"`
returns v0.52.2

**Comment by vredesbyyrd** [comment] 2018-09-17 01:00
Seeing the same on Arch linux and **Vte v0.54.1**.  Hmmmm.

```
Traceback (most recent call last):
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 24, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text, len(text) + 1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/crowbar.py", line 25, in _on_parent_set
    create_or_update_natilus_terminal(self)
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 53, in create_or_update_natilus_terminal
    vpanel._nt_instance.change_directory(crowbar.path)
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 135, in change_directory
    self._inject_command(" cd %s" % helpers.escape_path_for_shell(self._cwd))
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 175, in _inject_command
    _vte_terminal_feed_child(self._ui_terminal, "%s\n" % command)
  File "/home/clu/.local/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 27, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text)
TypeError: Must be number, not str

```

**Comment by flozz** [comment] 2018-09-17 11:56
That is strange, I used to have the same issue on Ubuntu but I cannot reproduce it anymore. Maybe Ubuntu or Debian patched something but GNOME not patched it yet (or the fix have not been released yet in Archlinux).

Can you try the code I posted here https://gitlab.gnome.org/GNOME/pygobject/issues/214 to see if it reproduce your issue? If yes, I will try again to find where this bug from and why I do not have it anymore...

**Comment by vredesbyyrd** [comment] 2018-09-17 13:45
So last night I had a hunch that maybe this had something to do with **python 3.7**, so I installed nautilus_terminal to use **python 2.7** instead (I do not have python 3.6 on system to test with).  Using python 2.7, Auto CD works without issue, and with no debugging errors. 

Here are the tests I ran. 

**Python 3.7** 

```
GI VERSION:   3.30.1
./test.py:15: PyGIDeprecationWarning: GLib.glib_version is deprecated; use (GLib.MAJOR_VERSION, GLib.MINOR_VERSION, GLib.MICRO_VERSION) instead
  print("GLIB VERSION: %i.%i.%i" % GLib.glib_version)
GLIB VERSION: 2.58.0
VTE VERSION:  0.54.1
ARGUMENTS:    Vte.Terminal.feed_child(gi.ArgInfo(text), gi.ArgInfo(length))
./test.py:33: DeprecationWarning: Vte.Terminal.spawn_sync is deprecated
  None, GLib.SpawnFlags.SEARCH_PATH, None, None)
Traceback (most recent call last):
  File "./test.py", line 35, in <module>
    term.feed_child(CMD, len(CMD))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

```
**Python 2.7**  

```
GI VERSION:   3.30.1
GLIB VERSION: 2.58.0
VTE VERSION:  0.54.1
ARGUMENTS:    Vte.Terminal.feed_child(gi.ArgInfo(text), gi.ArgInfo(length))
Traceback (most recent call last):
  File "./test.py", line 35, in <module>
    term.feed_child(CMD, len(CMD))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

```

**Comment by vredesbyyrd** [comment] 2018-09-20 01:08
> Oops, the example on the GNOME bug tracker is not up to date... 

Thank you for clarifying that. 

> ... But if it works it's ok :) 

Yeah I am totally cool with using it with python2 rather than 3. The few python modules  I have installed locally all use python2 to begin with, so its a little more neat that way.

**Comment by flozz** [comment] 2018-12-10 12:12
Ok... reading again this issue, it seems to be related to #27, I am waiting for feedback on the PR :)

**Comment by piekay** [comment] 2018-12-13 17:45
Fixed: But now the cd-command is displayed 2 times.

**Comment by flozz** [comment] 2020-08-16 12:14
Is this still an issue?

**Comment by vredesbyyrd** [comment] 2020-08-16 18:09
This is not an issue on my system, now on python 3.8. Nor is cd displayed twice.

**Comment by flozz** [comment] 2020-08-16 19:28
OK thank you, so I close this issue :)

**Closed by flozz** 2020-08-16 19:28 UTC
Labels: bug
