### ISSUE TITLE
Auto CD not working with non-English characters

### ISSUE THREAD

**Issue by City-busz** [flozz/nautilus-terminal#30] opened 2018-12-17 14:12 UTC
The automatic directory change does not work if the path contains non-English characters.

Package versions:
- nautilus 3.30.5
- python 3.7.1
- nautilus-python 1.2.2
- nautilus-terminal 3.2.3

Distribution:
- Arch Linux:

The output of ```NAUTILUS_TERMINAL_DEBUG=true nautilus```:
```
* Starting Nautilus Terminal
Initializing nautilus-image-converter extension
[Nautilus Terminal][ LOG] Crowbar inserted at /home/user
[Nautilus Terminal][ LOG] No NautilusTerminal instance found (new tab): creating a new NautilusTerminal...
[Nautilus Terminal][ LOG] backup_nautilus_accels: backuping accels...
[Nautilus Terminal][ LOG] NautilusTerminal._spawn_shell: Shell spawned (/bin/bash), PID: 11077.
[Nautilus Terminal][ LOG] remove_nautilus_accels: removing accels...
[Nautilus Terminal][ LOG] restore_nautilus_accels: restoring accels...
[Nautilus Terminal][ LOG] Crowbar inserted at /home/user/Képek
[Nautilus Terminal][ LOG] NautilusTerminal instance found: updating its path...
[Nautilus Terminal][ LOG] NautilusTerminal.change_directory: current directory changed to /home/user/Képek
[Nautilus Terminal][ LOG] NautilusTerminal._inject_command:  cd '/home/user/Képek'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 27, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text, len(text) + 1)
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/crowbar.py", line 25, in _on_parent_set
    create_or_update_natilus_terminal(self)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 56, in create_or_update_natilus_terminal
    vpanel._nt_instance.change_directory(crowbar.path)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 138, in change_directory
    self._inject_command(" cd %s" % helpers.escape_path_for_shell(self._cwd))
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 178, in _inject_command
    _vte_terminal_feed_child(self._ui_terminal, "%s\n" % command)
  File "/usr/lib/python3.7/site-packages/nautilus_terminal/nautilus_terminal.py", line 30, in _vte_terminal_feed_child
    return vte_terminal.feed_child(text)
OverflowError: 195 not in range -128 to 127
```

**Comment by tkachen** [comment] 2021-04-03 08:23
Seems like this was a problem in vte and it was [solved](https://gitlab.gnome.org/GNOME/vte/-/issues/201). I can't reproduce it on current version and old version mentioned in this issue.

**Comment by flozz** [comment] 2021-04-07 12:01
I close this issue as it seems to be a solved vte problem. Please open a new one if it is still broken. :)

**Closed by flozz** 2021-04-07 12:01 UTC
Labels: bug

**Comment by City-busz** [comment] 2021-04-30 08:56
Yes, it's fixed.
